      - name: Extract and test binaries
        run: |
          unzip shifocoin-linux-binaries.zip
          tar -xzf shifocoin-linux-x64.tar.gz
          cd shifocoin-release
          chmod +x bin/zcashd bin/zcash-cli bin/zcash-tx
          file bin/zcashd
          ls -la bin/
          mkdir -p ~/.zcash
          cat <<EOF > ~/.zcash/zcash.conf
          regtest=1
          rpcuser=shifoUser
          rpcpassword=StrongPassword1234!
          rpcallowip=127.0.0.1
          server=1
          txindex=1
          blocksonly=0
          daemon=1
          EOF
          ./bin/zcashd -regtest -daemon
          sleep 20
          tail -30 ~/.zcash/regtest/debug.log
