name: Build and Test Shifocoin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CC: gcc
  CXX: g++
  BUILD_DIR: build/
  INSTALL_DIR: shifocoin-release/

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
